### ISSUE TITLE
Error on dataset import page

### ISSUE THREAD

**Issue by rottoza** [OurWorldInData/owid-grapher#10]
Hi,
I get this error when going to the "import new data" menu:

`Next exception 'ErrorException' with message 'Trying to get property of non-object (View: /var/www/owid-grapher/resources/views/import/index.blade.php)' in /var/www/owid-grapher/storage/framework/views/11161acccbf6d47c6b03d0c410cd104b0c104b0ca63521.php:132`

I also notice that there is no categories, and no way to add categories.

I followed the installation instructions in the README.md file. Am i missing something?

**Comment by mispy** [comment]
Hello! Sorry about the mess-- this repo hasn't really been streamlined for external use or development yet. This is a good opportunity to clean it up a bit!

I've added the settings and categories and some other necessary stuff to the schema.sql dump, and double checked that the installation flow now works. (gulp is no longer necessary now, which is nice!)

**Comment by rottoza** [comment]
Hi there,
Thanks for the reply.

Any idea when it will be cleaned up?
Let me know if there is any way I can help.

**Comment by mispy** [comment]
It is functional now-- I've fixed that particular error and done an install run from scratch to verify that you can import data and make charts. Was there anything in particular you wanted to do with the code?

**Comment by rottoza** [comment]
I re-installed and imported a new dataset, but when I click on create new chart I get the following error:
`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'grapher.chart_types' doesn't exist (SQL: select `name`, `id` from `chart_types`)`

**Comment by mispy** [comment]
Ah, must have been leftovers in my local database. Give it a try now (shouldn't need to reload the db, just pull and refresh).

**Comment by rottoza** [comment]
Awesome thanks, seems to be working now.
Thanks for the quick help.
