### ISSUE TITLE
Error when editing dataset variable.

### ISSUE THREAD

**Issue by rottoza** [OurWorldInData/owid-grapher#11]
When editing and changing a dataset variable we get the following error:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list' (SQL: update `data_values` set `value` = 54.84, `updated_at` = 2016-08-19 06:20:22 where `id` = 3413091)`

**Comment by mispy** [comment]
Thanks for finding this bug! Fixed in master.

We usually update datasets by just importing the csv again, so regressions can pop up in the less-used editor stuff sometimes.
